// Expandable match-detail panels (head-to-head, lineups, stats, timeline) and the
// hook that fetches them. Split out of MatchRow.tsx to keep that file focused on
// the card itself. All four panels take plain team names + optional feed ids and
// render from /api/matchdetail (ESPN primary, API-Football fallback).
import { useState, useEffect, useRef } from 'react';
import { Users, BarChart2, Clock } from 'lucide-react';
import aflTeamIds from '../data/aflTeamIds.json';
import { normTeam } from '../data/teamMatch';
import type { TranslationKey } from '../data/i18n';

// ---------------------------------------------------------------------------
// H2H panel
// ---------------------------------------------------------------------------

interface H2HGame {
  date: string;
  homeTeam: string;
  awayTeam: string;
  homeScore: number | null;
  awayScore: number | null;
}

// Fetch head-to-head history from API-Football's /fixtures/headtohead endpoint
// (proxied via /api/afl). Unlike football-data.org's WC-only data, this returns
// real meetings across all competitions (friendlies, qualifiers, past World
// Cups). We look up each team's stable API-Football team ID by name, then cache
// results forever in localStorage since historical results never change.

// API-Football national-team IDs, keyed by the display names used in fixtures.
// Generated by scripts/fetch-afl-teams.mjs (see src/data/aflTeamIds.json).
const AFL_TEAM_IDS = aflTeamIds as unknown as Record<string, number>;

// Shape of a single fixture in the API-Football /fixtures/headtohead response.
interface AflH2HFixture {
  fixture: { date: string; status: { short: string } };
  league: { name: string };
  teams: { home: { name: string }; away: { name: string } };
  goals: { home: number | null; away: number | null };
}

type H2HState = 'idle' | 'loading' | 'loaded' | 'error';

export function H2HPanel({ team1, team2, t }: { team1: string; team2: string; t: (k: TranslationKey) => string }) {
  const [state, setState] = useState<H2HState>('idle');
  const [games, setGames] = useState<H2HGame[]>([]);
  const fetchedRef = useRef(false);

  useEffect(() => {
    if (fetchedRef.current) return;
    fetchedRef.current = true;

    const id1 = AFL_TEAM_IDS[team1];
    const id2 = AFL_TEAM_IDS[team2];

    if (!id1 || !id2) {
      // No known API-Football IDs — can't fetch H2H.
      setState('loaded');
      setGames([]);
      return;
    }

    // Key the cache by the (order-independent) ID pair so it's immutable.
    const cacheKey = `afl-h2h-${Math.min(id1, id2)}-${Math.max(id1, id2)}`;
    const cached = localStorage.getItem(cacheKey);
    if (cached) {
      try {
        setGames(JSON.parse(cached));
        setState('loaded');
        return;
      } catch {
        // corrupt cache — fall through to fetch
      }
    }

    setState('loading');

    // Note: the free plan ignores the "last" param and returns all H2H
    // fixtures; we filter to finished matches and keep the 5 most recent.
    fetch(`/api/afl/fixtures/headtohead?h2h=${id1}-${id2}`)
      .then((r) => {
        if (!r.ok) throw new Error('not ok');
        return r.json() as Promise<{ response?: AflH2HFixture[] }>;
      })
      .then((data) => {
        const h2h: H2HGame[] = (data.response ?? [])
          .filter((f) => f.fixture.status.short === 'FT')
          .sort(
            (a, b) =>
              new Date(b.fixture.date).getTime() - new Date(a.fixture.date).getTime()
          )
          .slice(0, 5)
          .map((f) => ({
            date: f.fixture.date.slice(0, 4),
            homeTeam: f.teams.home.name,
            awayTeam: f.teams.away.name,
            homeScore: f.goals.home,
            awayScore: f.goals.away,
          }));

        localStorage.setItem(cacheKey, JSON.stringify(h2h));
        setGames(h2h);
        setState('loaded');
      })
      .catch(() => {
        setState('error');
      });
  }, [team1, team2]);

  if (state === 'loading') {
    return (
      <div className="text-xs text-neutral-400 flex items-center gap-2 py-1">
        <span className="inline-block w-3 h-3 rounded-full border-2 border-neutral-300 border-t-[var(--accent)] animate-spin" />
        {t('h2hLoading')}
      </div>
    );
  }

  if (state === 'error') {
    return <div className="text-xs text-neutral-400 py-1">{t('h2hError')}</div>;
  }

  if (state === 'loaded' && games.length === 0) {
    return <div className="text-xs text-neutral-400 py-1">{t('h2hNoData')}</div>;
  }

  return (
    <div className="space-y-1">
      <div className="text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wide mb-1">
        {t('h2hHistory')}
      </div>
      {games.map((g, i) => (
        <div key={i} className="flex items-center gap-2 text-xs text-neutral-600 dark:text-neutral-400">
          <span className="w-10 text-right text-neutral-400">{g.date}</span>
          <span className="flex-1 truncate">{g.homeTeam}</span>
          <span className="font-mono font-semibold text-neutral-800 dark:text-neutral-200 tabular-nums">
            {g.homeScore ?? '?'}&ndash;{g.awayScore ?? '?'}
          </span>
          <span className="flex-1 truncate">{g.awayTeam}</span>
        </div>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Match detail — lineups + statistics (batched from a single /api/matchdetail)
// ---------------------------------------------------------------------------

interface PlayerEntry {
  id: number;
  name: string;
  shirtNumber?: number;
  position?: string;
}

interface TeamLineup {
  lineup: PlayerEntry[];
  bench: PlayerEntry[];
}

interface MatchEvent { minute: string; kind: string; team: string; player: string; detail?: string }

interface MatchDetailData {
  source: string | null;
  homeLineup: TeamLineup;
  awayLineup: TeamLineup;
  stats: StatRow[];
  events: MatchEvent[];
}

type DetailState = 'idle' | 'loading' | 'loaded' | 'error';

// normTeam (with feed aliases) is the shared, test-guarded one — see teamMatch.ts.

// Shape returned by our /api/matchdetail endpoint (ESPN with API-Football
// fallback, normalised server-side into one shape).
interface MdPlayer { id: number; name: string; number?: number; position?: string }
interface MdTeam { name: string; formation?: string; startXI: MdPlayer[]; bench: MdPlayer[]; stats: Record<string, string> }

function mdToLineup(t: MdTeam | undefined): TeamLineup {
  const map = (a?: MdPlayer[]): PlayerEntry[] =>
    (a ?? []).map((p, i) => ({ id: p.id || i, name: p.name, shirtNumber: p.number, position: p.position }));
  return { lineup: map(t?.startXI), bench: map(t?.bench) };
}

// Hook: lineups + stats for a match via /api/matchdetail, keyed by the ESPN
// event id (primary) or API-Football fixture id (fallback) the poller attached.
// No id → not live / not available → no data and NO upstream call. Shows cached
// values instantly, then refreshes every 75s while open (edge-cached upstream).
export function useMatchDetail(
  homeTeam: string,
  awayTeam: string,
  espnEventId: string | undefined,
  aflFixtureId: number | undefined,
): { state: DetailState; detail: MatchDetailData | null } {
  const [state, setState] = useState<DetailState>('idle');
  const [detail, setDetail] = useState<MatchDetailData | null>(null);

  useEffect(() => {
    if (!espnEventId && !aflFixtureId) { setState('loaded'); setDetail(null); return; }

    let cancelled = false;
    const cacheKey = `md-${espnEventId ?? 'afl' + aflFixtureId}`;
    const cached = localStorage.getItem(cacheKey);
    if (cached) {
      try { setDetail(JSON.parse(cached) as MatchDetailData); setState('loaded'); } catch { /* corrupt */ }
    } else {
      setState('loading');
    }

    const n1 = normTeam(homeTeam);
    const load = async () => {
      try {
        const params = new URLSearchParams();
        if (espnEventId) params.set('espn', espnEventId);
        if (aflFixtureId) params.set('afl', String(aflFixtureId));
        const r = await fetch(`/api/matchdetail?${params.toString()}`);
        if (!r.ok) return;
        const j = (await r.json()) as { source: string | null; teams: MdTeam[]; events?: MatchEvent[] };
        const teams = j.teams ?? [];
        const events = j.events ?? [];
        if (teams.length < 2 && events.length === 0) { if (!cancelled && !cached) setState('loaded'); return; }
        const homeT = teams.find((tm) => normTeam(tm.name) === n1) ?? teams[0] ?? { name: homeTeam, startXI: [], bench: [], stats: {} };
        const awayT = teams.find((tm) => tm !== homeT) ?? teams[1] ?? { name: awayTeam, startXI: [], bench: [], stats: {} };
        const stats: StatRow[] = STAT_ORDER
          .filter((k) => homeT.stats[k] != null || awayT.stats[k] != null)
          .map((k) => ({ type: k, home: homeT.stats[k] ?? null, away: awayT.stats[k] ?? null }));
        const md: MatchDetailData = {
          source: j.source,
          homeLineup: mdToLineup(homeT),
          awayLineup: mdToLineup(awayT),
          stats,
          events,
        };
        if (cancelled) return;
        const hasData = md.homeLineup.lineup.length > 0 || md.awayLineup.lineup.length > 0 || md.stats.length > 0 || md.events.length > 0;
        if (hasData) localStorage.setItem(cacheKey, JSON.stringify(md));
        setDetail(md);
        setState('loaded');
      } catch {
        if (!cancelled && !cached) setState('error');
      }
    };

    void load();
    const id = setInterval(() => void load(), 75_000);
    return () => { cancelled = true; clearInterval(id); };
  }, [homeTeam, awayTeam, espnEventId, aflFixtureId]);

  return { state, detail };
}

// ---------------------------------------------------------------------------
// Lineups panel
// ---------------------------------------------------------------------------

function PlayerList({ players, t }: { players: PlayerEntry[]; t: (k: TranslationKey) => string }) {
  if (players.length === 0) {
    return <div className="text-xs text-neutral-400 italic">{t('lineupsNoData')}</div>;
  }
  return (
    <ul className="space-y-0.5">
      {players.map((p) => (
        <li key={p.id} className="flex items-center gap-1.5 text-xs text-neutral-700 dark:text-neutral-300">
          {p.shirtNumber !== undefined && (
            <span className="w-5 text-right tabular-nums text-neutral-400 dark:text-neutral-500 flex-shrink-0 font-mono text-[11px]">
              {p.shirtNumber}
            </span>
          )}
          <span className="truncate">{p.name}</span>
          {p.position && (
            <span className="ml-auto text-[10px] uppercase tracking-wide text-neutral-400 flex-shrink-0">
              {p.position.slice(0, 3)}
            </span>
          )}
        </li>
      ))}
    </ul>
  );
}

export function LineupsPanel({
  homeTeam,
  awayTeam,
  espnEventId,
  aflFixtureId,
  t,
}: {
  homeTeam: string;
  awayTeam: string;
  espnEventId?: string;
  aflFixtureId?: number;
  t: (k: TranslationKey) => string;
}) {
  const { state, detail } = useMatchDetail(homeTeam, awayTeam, espnEventId, aflFixtureId);

  if (state === 'loading' || state === 'idle') {
    return (
      <div className="text-xs text-neutral-400 flex items-center gap-2 py-1">
        <span className="inline-block w-3 h-3 rounded-full border-2 border-neutral-300 border-t-[var(--accent)] animate-spin" />
        {t('lineupsLoading')}
      </div>
    );
  }

  if (state === 'error') {
    return <div className="text-xs text-neutral-400 py-1">{t('lineupsError')}</div>;
  }

  if (!detail || (detail.homeLineup.lineup.length === 0 && detail.awayLineup.lineup.length === 0)) {
    return <div className="text-xs text-neutral-400 py-1">{t('lineupsNoData')}</div>;
  }

  return (
    <div>
      <div className="text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wide mb-2 flex items-center gap-1.5">
        <Users size={12} />
        {t('lineups')}
      </div>
      <div className="grid grid-cols-2 gap-x-4">
        {/* Home */}
        <div>
          <div className="text-[11px] font-semibold text-neutral-500 dark:text-neutral-400 mb-1 truncate">{homeTeam}</div>
          <div className="text-[10px] uppercase tracking-wide text-neutral-400 mb-0.5">{t('startingXI')}</div>
          <PlayerList players={detail.homeLineup.lineup} t={t} />
          {detail.homeLineup.bench.length > 0 && (
            <>
              <div className="text-[10px] uppercase tracking-wide text-neutral-400 mt-2 mb-0.5">{t('bench')}</div>
              <PlayerList players={detail.homeLineup.bench} t={t} />
            </>
          )}
        </div>
        {/* Away */}
        <div>
          <div className="text-[11px] font-semibold text-neutral-500 dark:text-neutral-400 mb-1 truncate">{awayTeam}</div>
          <div className="text-[10px] uppercase tracking-wide text-neutral-400 mb-0.5">{t('startingXI')}</div>
          <PlayerList players={detail.awayLineup.lineup} t={t} />
          {detail.awayLineup.bench.length > 0 && (
            <>
              <div className="text-[10px] uppercase tracking-wide text-neutral-400 mt-2 mb-0.5">{t('bench')}</div>
              <PlayerList players={detail.awayLineup.bench} t={t} />
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Statistics panel — possession, shots, corners, fouls, cards, pass accuracy
// from /api/matchdetail (ESPN primary, API-Football fallback). Canonical keys.
// ---------------------------------------------------------------------------

interface StatRow {
  type: string;
  home: string | number | null;
  away: string | number | null;
}

// Canonical stat key → existing i18n key.
const STAT_LABEL_KEYS: Record<string, TranslationKey> = {
  possession: 'statPossession',
  shots: 'statShots',
  shotsOnTarget: 'statShotsOnGoal',
  corners: 'statCorners',
  fouls: 'statFouls',
  offsides: 'statOffsides',
  yellowCards: 'statYellowCards',
  redCards: 'statRedCards',
  saves: 'statSaves',
};
const STAT_RAW_LABELS: Record<string, string> = {
  passAccuracy: 'Pass accuracy',
};
const STAT_ORDER = [
  'possession', 'shots', 'shotsOnTarget', 'corners', 'fouls',
  'offsides', 'yellowCards', 'redCards', 'saves', 'passAccuracy',
];

function toStatNum(v: string | number | null): number {
  if (typeof v === 'number') return v;
  if (typeof v === 'string') return parseFloat(v.replace('%', '')) || 0;
  return 0;
}

function StatBar({ value, max, side }: { value: number; max: number; side: 'home' | 'away' }) {
  const pct = max > 0 ? Math.min(Math.round((value / max) * 100), 100) : 0;
  return (
    <div
      className={['h-1.5 rounded-full bg-[var(--accent)] transition-all', side === 'away' ? 'ml-auto' : ''].join(' ')}
      style={{ width: `${pct}%` }}
    />
  );
}

export function StatsPanel({ homeTeam, awayTeam, espnEventId, aflFixtureId, t }: { homeTeam: string; awayTeam: string; espnEventId?: string; aflFixtureId?: number; t: (k: TranslationKey) => string }) {
  const { state, detail } = useMatchDetail(homeTeam, awayTeam, espnEventId, aflFixtureId);
  const rows = detail?.stats ?? null;

  if (state === 'loading' || state === 'idle') {
    return (
      <div className="text-xs text-neutral-400 flex items-center gap-2 py-1">
        <span className="inline-block w-3 h-3 rounded-full border-2 border-neutral-300 border-t-[var(--accent)] animate-spin" />
        {t('statsLoading')}
      </div>
    );
  }
  if (state === 'error') return <div className="text-xs text-neutral-400 py-1">{t('statsError')}</div>;
  if (!rows || rows.length === 0) return <div className="text-xs text-neutral-400 py-1">{t('statsNoData')}</div>;

  return (
    <div>
      <div className="text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wide mb-2 flex items-center gap-1.5">
        <BarChart2 size={12} />
        {t('matchStats')}
      </div>
      <div className="space-y-2">
        {rows.map((row) => {
          const labelKey = STAT_LABEL_KEYS[row.type];
          const label = labelKey ? t(labelKey) : (STAT_RAW_LABELS[row.type] ?? row.type);
          const isPct = row.type === 'possession' || row.type === 'passAccuracy';
          const hv = toStatNum(row.home);
          const av = toStatNum(row.away);
          const max = isPct ? 100 : Math.max(hv, av, 1);
          return (
            <div key={row.type}>
              <div className="flex items-center text-xs text-neutral-700 dark:text-neutral-300">
                <span className="w-12 tabular-nums font-semibold">{row.home ?? '-'}</span>
                <span className="flex-1 text-center text-[11px] text-neutral-400 dark:text-neutral-500">{label}</span>
                <span className="w-12 tabular-nums font-semibold text-right">{row.away ?? '-'}</span>
              </div>
              <div className="flex items-center gap-1 mt-0.5">
                <div className="flex-1"><StatBar value={hv} max={max} side="home" /></div>
                <div className="flex-1"><StatBar value={av} max={max} side="away" /></div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Timeline panel — goals / cards / subs with player + minute, from /api/matchdetail.
// ---------------------------------------------------------------------------

const EVENT_ICON: Record<string, string> = {
  goal: '⚽',
  own: '⚽',
  pen: '⚽',
  yellow: '🟨',
  red: '🟥',
  sub: '🔁',
  'pens-start': '🎯',
  'pens-score': '⚽',
  'pens-save': '🧤',
  'pens-miss': '❌',
  'pens-end': '🏁',
};

export function TimelinePanel({ homeTeam, awayTeam, espnEventId, aflFixtureId, t }: {
  homeTeam: string; awayTeam: string; espnEventId?: string; aflFixtureId?: number; t: (k: TranslationKey) => string;
}) {
  const { state, detail } = useMatchDetail(homeTeam, awayTeam, espnEventId, aflFixtureId);
  const events = detail?.events ?? null;

  if (state === 'loading' || state === 'idle') {
    return (
      <div className="text-xs text-neutral-400 flex items-center gap-2 py-1">
        <span className="inline-block w-3 h-3 rounded-full border-2 border-neutral-300 border-t-[var(--accent)] animate-spin" />
        {t('eventsLoading')}
      </div>
    );
  }
  if (state === 'error') return <div className="text-xs text-neutral-400 py-1">{t('eventsError')}</div>;
  if (!events || events.length === 0) return <div className="text-xs text-neutral-400 py-1">{t('eventsNoData')}</div>;

  return (
    <div>
      <div className="text-xs font-semibold text-neutral-500 dark:text-neutral-400 uppercase tracking-wide mb-2 flex items-center gap-1.5">
        <Clock size={12} />
        {t('timeline')}
      </div>
      <ul className="space-y-1">
        {events.map((e, i) => (
          <li key={i} className="flex items-center gap-2 text-xs text-neutral-700 dark:text-neutral-300">
            <span className="w-9 text-right tabular-nums text-neutral-400 dark:text-neutral-500 flex-shrink-0 font-mono">{e.minute}</span>
            <span className="flex-shrink-0">{EVENT_ICON[e.kind] ?? '•'}</span>
            <span className="truncate font-medium">{e.player || e.detail}</span>
            <span className="ml-auto text-[10px] uppercase tracking-wide text-neutral-400 flex-shrink-0 truncate max-w-[35%]">{e.team}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
